<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>

    <AssemblyName>VGAudioCli</AssemblyName>
    <AssemblyTitle>VGAudio.Cli</AssemblyTitle>
    <Copyright>Copyright © 2016 Alex Barney</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VGAudio\VGAudio.csproj" />
  </ItemGroup>

</Project>
